apiVersion: v1
kind: Pod
metadata:
  name: sebastian-service-pod
  labels:
    app: sebastian-service
spec:
  containers:
    - name: sebastian-service-container
      image: seb0927/msvc_sebastian:latest
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: sebastian-service-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: sebastian-service
