apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-carlos
data:
  port: "8009"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-carlos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-carlos
  template:
    metadata:
      labels:
        app: msvc-carlos
    spec:
      containers:
        - image: carloshot007/msvc-carlos:latest
          name: msvc-carlos
          ports:
            - containerPort: 8009
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-carlos
                  key: port
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-carlos
spec: 
  type: LoadBalancer
  ports:
    - port: 8009
      targetPort: 8009
      protocol: TCP
  selector:
    app: msvc-carlos
