apiVersion: v1
kind: Pod
metadata:
  name: servicio-mmg-pod
  labels:
    app: servicio-mmg
spec:
  containers:
    - name: servicio-mmg-container
      image: maumg03/serviciommg:latest
      ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-mmg-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: servicio-mmg