apiVersion: v1
kind: Pod
metadata:
  name: carlos-pod
  labels:
    app: msvc-carlos
spec:
  containers:
    - name: msvc-carlos
      image: carloshot007/msvc-carlos:latest
      ports:
        - containerPort: 8009
---
apiVersion: v1
kind: Service
metadata:
  name: carlos-service
spec: 
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8009
      protocol: TCP
  selector:
    app: msvc-carlos
